### ISSUE TITLE
apig-test quits unexpectedly

### ISSUE THREAD

**Issue by danielkaczmarczyk** [AnomalyInnovations/serverless-stack-demo-api#10]
Hey, I'm following the Test The APIs steps from https://serverless-stack.com/chapters/test-the-apis.html, and I am not able to succeed. Running this command (obv with my own creds):

`$ apig-test \
--username='admin@example.com' \
--password='Passw0rd!' \
--user-pool-id='YOUR_COGNITO_USER_POOL_ID' \
--app-client-id='YOUR_COGNITO_APP_CLIENT_ID' \
--cognito-region='YOUR_COGNITO_REGION' \
--identity-pool-id='YOUR_IDENTITY_POOL_ID' \
--invoke-url='YOUR_API_GATEWAY_URL' \
--api-gateway-region='YOUR_API_GATEWAY_REGION' \
--path-template='/notes' \
--method='POST' \
--body='{"content":"hello world","attachment":"hello.jpg"}'`

Is returning this:

```Authenticating with User Pool
Getting temporary credentials
Making API request
/Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-cli-test/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property '1' of null
    at Object.apigClientFactory.newClient (/Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-client/dist/apigClient.js:65:57)
    at makeRequest (/Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-cli-test/index.js:157:38)
    at /Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-cli-test/index.js:150:5
    at /Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-cli-test/node_modules/aws-sdk/lib/credentials.js:123:23
    at Response.<anonymous> (/Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-cli-test/node_modules/aws-sdk/lib/credentials/cognito_identity_credentials.js:258:7)
    at Request.<anonymous> (/Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-cli-test/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-cli-test/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-cli-test/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-cli-test/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/danielkaczmarczyk/Desktop/serverless/notes-app-api/node_modules/aws-api-gateway-cli-test/node_modules/aws-sdk/lib/request.js:22:10)```



I was trying to figure out what's happening to no avail. Checked DynamoDb and Lambda - no resources are created nor any function is being invoked. please help!

**Comment by danielkaczmarczyk** [comment]
ok, consider it closed, I have simply not included the proper `invoke-url`!
